# Generated by Django 6.1 on 2026-08-20 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='flavour',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='key_benefits',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='life_stage',
            field=models.CharField(blank=True, choices=[('puppy_kitten', 'Puppy / Kitten'), ('adult', 'Adult'), ('senior', 'Senior'), ('all', 'All Life Stages')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pet_type',
            field=models.CharField(blank=True, choices=[('dog', 'Dog'), ('cat', 'Cat'), ('both', 'Dog & Cat')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('dog_food', 'Dog Food'), ('dog_treat', 'Dog Treats'), ('dog_toy', 'Dog Toys'), ('dog_grooming', 'Dog Grooming'), ('dog_accessory', 'Dog Accessories'), ('dog_health', 'Dog Health'), ('cat_food', 'Cat Food'), ('cat_treat', 'Cat Treats'), ('cat_toy', 'Cat Toys'), ('cat_litter', 'Cat Litter'), ('cat_grooming', 'Cat Grooming'), ('cat_accessory', 'Cat Accessories'), ('cat_health', 'Cat Health'), ('medicine', 'Medicine'), ('supplement', 'Supplements'), ('skin_coat', 'Skin & Coat'), ('dental', 'Dental Care'), ('joint_care', 'Joint Care'), ('digestive', 'Digestive Care'), ('treat', 'Treat'), ('accessory', 'Accessory')], max_length=50),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product')),
            ],
        ),
    ]
