# Generated by Django 6.1 on 2026-08-20 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_orderitem_variant_orderitem_variant_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedingGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('daily_grams', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_guides', to='store.product')),
            ],
        ),
    ]
