# Generated by Django 6.1 on 2026-08-22 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_productvariant_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('image_type', models.CharField(choices=[('gallery', 'Gallery'), ('ingredients', 'Ingredients'), ('nutrition', 'Nutrition'), ('feeding', 'Feeding Guide'), ('lifestyle', 'Lifestyle'), ('other', 'Other')], default='gallery', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='store.product')),
            ],
        ),
    ]
