# Generated by Django 6.1 on 2026-09-08 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_order_checkout_token_order_razorpay_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=40)),
                ('state', models.CharField(default='attempting', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_deliveries', to='store.order')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('order', 'event'), name='unique_order_email_event')],
            },
        ),
    ]
