from django.urls import path
from . import views, commerce_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("", views.home, name="home"),
    path("delivery/check/", commerce_views.delivery_status, name="delivery_status"),
    path("quick-view/<int:product_id>/", commerce_views.quick_view, name="quick_view"),
    path("product/<int:product_id>/frequently-bought/add/", commerce_views.add_frequently_bought, name="add_frequently_bought"),
    path("offers/", commerce_views.offers, name="offers"),
    path("bundles/<slug:slug>/", commerce_views.bundle_detail, name="bundle_detail"),
    path("bundles/<slug:slug>/add/", commerce_views.add_bundle, name="add_bundle"),
    path("bundles/<int:bundle_id>/remove/", commerce_views.remove_bundle, name="remove_bundle"),
    path("prescriptions/upload/<int:product_id>/", commerce_views.prescription_upload, name="prescription_upload"),
    path("prescriptions/<int:prescription_id>/file/", commerce_views.prescription_download, name="prescription_download"),
    path("crm/delivery-zones/", commerce_views.crm_delivery_zones, name="crm_delivery_zones"),
    path("crm/delivery-zones/<int:zone_id>/", commerce_views.crm_delivery_zones, name="crm_delivery_zone_edit"),
    path("crm/offers/", commerce_views.crm_offers, name="crm_offers"),
    path("crm/offers/<int:campaign_id>/", commerce_views.crm_offers, name="crm_offer_edit"),
    path("crm/bundles/", commerce_views.crm_bundles, name="crm_bundles"),
    path("crm/bundles/products/search/", commerce_views.crm_bundle_product_search, name="crm_bundle_product_search"),
    path("crm/bundles/variants/search/", commerce_views.crm_bundle_variant_search, name="crm_bundle_variant_search"),
    path("crm/bundles/<int:bundle_id>/", commerce_views.crm_bundles, name="crm_bundle_edit"),
    path("crm/prescriptions/", commerce_views.crm_prescriptions, name="crm_prescriptions"),
    path("crm/prescriptions/<int:prescription_id>/review/", commerce_views.crm_prescription_review, name="crm_prescription_review"),

    path("cart/", views.cart, name="cart"),
    path("cart/add/<int:product_id>/", views.add_to_cart, name="add_to_cart"),
    path("cart/buy-now/<int:product_id>/", views.buy_now, name="buy_now"),
    path("cart/remove/<int:product_id>/", views.remove_from_cart, name="remove_from_cart"),
    path("cart/increase/<int:product_id>/", views.increase_quantity, name="increase_quantity"),
    path("cart/decrease/<int:product_id>/", views.decrease_quantity, name="decrease_quantity"),
    path("cart/coupon/", views.apply_coupon, name="apply_coupon"),

    path("checkout/", views.checkout, name="checkout"),
    path("order-success/<int:order_id>/", views.order_success, name="order_success"),
    path("register/", views.register_view, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("account/", views.account, name="account"),
    path("pets/", views.my_pets, name="my_pets"),
    path("pets/add/", views.add_pet, name="add_pet"),
    path("pets/<int:pet_id>/edit/", views.edit_pet, name="edit_pet"),
    path("orders/", views.my_orders, name="my_orders"),
    path("crm/", views.crm_dashboard, name="crm_dashboard"),
    path("crm/customers/", views.crm_customers, name="crm_customers"),
    path("crm/customers/<int:user_id>/", views.crm_customer_detail, name="crm_customer_detail"),
    path("orders/<int:order_id>/", views.order_detail, name="order_detail"),
    path("orders/<int:order_id>/reorder/", views.reorder, name="reorder"),
    path("crm/inventory/", views.crm_inventory, name="crm_inventory"),
    path("crm/inventory/<int:product_id>/edit/", views.crm_inventory_edit, name="crm_inventory_edit"),
    path("crm/inventory/<int:product_id>/archive/", views.crm_inventory_archive, name="crm_inventory_archive"),
    path("crm/inventory/<int:product_id>/restore/", views.crm_inventory_restore, name="crm_inventory_restore"),
    path("crm/orders/", views.crm_orders, name="crm_orders"),
    path("crm/orders/<int:order_id>/status/", views.crm_order_status, name="crm_order_status"),
    path("crm/reports/", views.crm_reports, name="crm_reports"),
    path("crm/coupons/", views.crm_coupons, name="crm_coupons"),
    path("crm/coupons/<int:coupon_id>/edit/", views.crm_coupons, name="crm_coupon_edit"),
    path("crm/inventory/add/", views.crm_inventory_add, name="crm_inventory_add"),
    path("product/<int:product_id>/", views.product_detail, name="product_detail"),
    path("product/<int:product_id>/review/",views.add_review,name="add_review"),
    path("dogs/", views.dog_products, name="dog_products"),
    path("cats/", views.cat_products, name="cat_products"),
    path("medicines/", views.medicine_products, name="medicine_products"),
    path("wellness/", views.wellness_products, name="wellness_products"),
    path("grooming-hygiene/", views.grooming_products, name="grooming_products"),
    path("birds/", views.bird_products, name="bird_products"),
    path("small-pets/", views.small_pet_products, name="small_pet_products"),
    path("farm-animals/", views.farm_animal_products, name="farm_animal_products"),
    path("fish-reptiles/", views.fish_reptile_products, name="fish_reptile_products"),
    path("vaccination/", views.vaccination_products, name="vaccination_products"),
    path("help/contact/", views.contact_page, name="contact_page"),
    path("help/faq/", views.faq_page, name="faq_page"),
    path("policies/shipping/", views.shipping_policy, name="shipping_policy"),
    path("policies/returns/", views.returns_policy, name="returns_policy"),
    path("policies/veterinary-medicines/", views.veterinary_disclaimer, name="veterinary_disclaimer"),
    path("policies/privacy/", views.privacy_policy, name="privacy_policy"),
    path("policies/terms/", views.terms_page, name="terms_page"),
    path("search/", views.search_products, name="search_products"),
    path("wishlist/", views.wishlist, name="wishlist"),
    path("wishlist/toggle/<int:product_id>/",views.toggle_wishlist,name="toggle_wishlist"),
    path("addresses/",views.my_addresses,name="my_addresses"),
    path("addresses/add/",views.add_address,name="add_address"),
    path("addresses/<int:address_id>/edit/",views.edit_address,name="edit_address"),
    path("addresses/<int:address_id>/delete/",views.delete_address,name="delete_address"),
    path("payment/verify/",views.verify_payment,name="verify_payment"),
   path(
    "payment/retry/<int:order_id>/",
    views.retry_payment,
    name="retry_payment"
),
    path("payment/failed/<int:order_id>/",views.payment_failed_view,name="payment_failed_view"),
    path("payment/cancelled/<int:order_id>/",views.payment_cancelled,name="payment_cancelled"),
    path(
    "password-reset/",
    auth_views.PasswordResetView.as_view(
        template_name="store/password_reset.html",
        email_template_name="store/emails/password_reset_email.html",
        subject_template_name="store/emails/password_reset_subject.txt",
    ),
    name="password_reset",
),

path(
    "password-reset/done/",
    auth_views.PasswordResetDoneView.as_view(
        template_name="store/password_reset_done.html"
    ),
    name="password_reset_done",
),

path(
    "password-reset/<uidb64>/<token>/",
    auth_views.PasswordResetConfirmView.as_view(
        template_name="store/password_reset_confirm.html"
    ),
    name="password_reset_confirm",
),

path(
    "password-reset/complete/",
    auth_views.PasswordResetCompleteView.as_view(
        template_name="store/password_reset_complete.html"
    ),
    name="password_reset_complete",
),
path(
    "crm/inventory/bulk-import/",
    views.crm_inventory_bulk_import,
    name="crm_inventory_bulk_import",
),
path(
    "crm/inventory/images/",
    views.crm_bulk_images,
    name="crm_bulk_images",
),
]
