"""
Django settings for petcare project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""
import os
import sys
import dj_database_url
import truststore
from pathlib import Path
from dotenv import dotenv_values
from django.core.exceptions import ImproperlyConfigured

# Python's bundled CA file can reject certificates issued through the Windows
# trust chain (common with antivirus/web protection). Use the operating-system
# certificate store for outbound HTTPS calls such as Google OAuth.
truststore.inject_into_ssl()

BASE_DIR = Path(__file__).resolve().parent.parent

env = {
    **dotenv_values(BASE_DIR / ".env"),
    **os.environ,
}

CLOUDINARY_STORAGE = {
    "CLOUD_NAME": (
        env.get("CLOUDINARY_CLOUD_NAME") or ""
    ).strip(),

    "API_KEY": (
        env.get("CLOUDINARY_API_KEY") or ""
    ).strip(),

    "API_SECRET": (
        env.get("CLOUDINARY_API_SECRET") or ""
    ).strip(),
}

RAZORPAY_KEY_ID = (
    env.get("RAZORPAY_KEY_ID") or ""
).strip()

RAZORPAY_KEY_SECRET = (
    env.get("RAZORPAY_KEY_SECRET") or ""
).strip()
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = (
    env.get("DJANGO_SECRET_KEY") or ""
).strip()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = (
    env.get("DEBUG", "False").lower()
    == "true"
)

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "bows-and-meows-1.onrender.com",
]
CSRF_TRUSTED_ORIGINS = [
    "https://bows-and-meows-1.onrender.com",
]

render_hostname = (env.get("RENDER_EXTERNAL_HOSTNAME") or "").strip()
IS_RENDER = bool(render_hostname)

if IS_RENDER and (
    len(SECRET_KEY) < 50
    or SECRET_KEY.startswith("django-insecure-")
    or SECRET_KEY.startswith("replace-")
):
    raise ImproperlyConfigured(
        "Render requires a unique DJANGO_SECRET_KEY containing at least 50 characters."
    )

if render_hostname:
    # Render terminates TLS at its proxy. Force production-safe behavior even
    # if a stale DEBUG environment variable was accidentally left enabled.
    DEBUG = False
    ALLOWED_HOSTS.append(render_hostname)
    CSRF_TRUSTED_ORIGINS.append(
        f"https://{render_hostname}"
    )

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = IS_RENDER
CSRF_COOKIE_SECURE = IS_RENDER
SECURE_HSTS_SECONDS = int(
    (env.get("DJANGO_SECURE_HSTS_SECONDS") or "0").strip()
)
# Start with a short host-only HSTS policy. Subdomains/preload remain opt-in
# until the production domain and every subdomain have been verified on HTTPS.
SECURE_HSTS_INCLUDE_SUBDOMAINS = (
    (env.get("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS") or "False").lower() == "true"
)
SECURE_HSTS_PRELOAD = (
    (env.get("DJANGO_SECURE_HSTS_PRELOAD") or "False").lower() == "true"
)
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
X_FRAME_OPTIONS = "DENY"
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sites',

    'django.contrib.staticfiles',

    'cloudinary_storage',
    'cloudinary',

    'store',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'petcare.urls'
SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

GOOGLE_OAUTH_CLIENT_ID = (env.get("GOOGLE_OAUTH_CLIENT_ID") or "").strip()
GOOGLE_OAUTH_CLIENT_SECRET = (env.get("GOOGLE_OAUTH_CLIENT_SECRET") or "").strip()
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APPS": [{
            "client_id": GOOGLE_OAUTH_CLIENT_ID,
            "secret": GOOGLE_OAUTH_CLIENT_SECRET,
            "key": "",
        }],
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
        "VERIFIED_EMAIL": True,
    }
}
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_ADAPTER = "store.adapters.GoogleAccountAdapter"
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'store.context_processors.customer_support',
            ],
        },
    },
]

WSGI_APPLICATION = 'petcare.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASE_URL = (
    env.get("DATABASE_URL") or ""
).strip()

if DATABASE_URL:

    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }

else:

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },

    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
if "test" in sys.argv:
    # Tests must be deterministic and must never upload private/user files or
    # depend on a previously generated production static manifest.
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }
# Transactional email. Local development defaults to the console. When a
# Brevo API key is present, production uses Brevo's HTTPS API so it also works
# on hosts that block outbound SMTP ports.
BREVO_API_KEY = (env.get("BREVO_API_KEY") or "").strip()
BREVO_SENDER_EMAIL = (env.get("BREVO_SENDER_EMAIL") or "").strip()
BREVO_SENDER_NAME = (env.get("BREVO_SENDER_NAME") or "Boww & Meow").strip()
EMAIL_BACKEND = (
    env.get("EMAIL_BACKEND")
    or (
        "store.email_backend.BrevoAPIEmailBackend"
        if BREVO_API_KEY
        else "django.core.mail.backends.console.EmailBackend"
    )
).strip()
EMAIL_HOST = (env.get("EMAIL_HOST") or "smtp.gmail.com").strip()
EMAIL_PORT = int((env.get("EMAIL_PORT") or "587").strip())
EMAIL_USE_TLS = (env.get("EMAIL_USE_TLS") or "True").lower() == "true"
EMAIL_TIMEOUT = int((env.get("EMAIL_TIMEOUT") or "10").strip())

EMAIL_HOST_USER = (
    env.get("EMAIL_HOST_USER") or ""
).strip()

EMAIL_HOST_PASSWORD = (
    env.get("EMAIL_HOST_PASSWORD") or ""
).strip()

DEFAULT_FROM_EMAIL = (
    env.get("DEFAULT_FROM_EMAIL")
    or (f"{BREVO_SENDER_NAME} <{BREVO_SENDER_EMAIL}>" if BREVO_SENDER_EMAIL else "")
    or EMAIL_HOST_USER
    or "Boww & Meow <noreply@bowsandmeows.com>"
).strip()
STOREFRONT_BASE_URL = (
    env.get("STOREFRONT_BASE_URL")
    or (f"https://{render_hostname}" if render_hostname else "http://127.0.0.1:8000")
).rstrip("/")
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"
WHATSAPP_NUMBER = (env.get("WHATSAPP_NUMBER") or "").strip()
SUPPORT_EMAIL = (env.get("SUPPORT_EMAIL") or EMAIL_HOST_USER or "").strip()
